### ISSUE TITLE
This mod conflicts with Better End Blossoming Spheres with Connector and Embeddium 1.20.1

### ISSUE THREAD

**Issue by lSherozl** [MCTeamPotato/Kasualix-Issue-Tracker#164]
### Specific mod for which you open this issue

Redirectior

### MC version & mod version & loader version

Redirector 5.00

### Latest log

https://pastebin.com/hygRKxj4

### Steps to reproduce your issue

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/6e02494a-c285-4d4d-b492-a9292ba48023">
Something to do with Blossoming spheres from better end, take a look at the block type in the upper left corner, The error occurs when Sodium attempts to build chunk meshes for rendering. The problematic block seems to be minecraft:purple_stained_glass_pane, where Sodium is unable to retrieve a property (null) that it expects. REMOVING REDIRECTOR does fix the issue so I know it is not embeddium itself.

**Comment by lSherozl** [comment]
Only part of log thats relevant: [17Nov2024 02:18:22.660] [Render thread/INFO] [Figura/]: Cleared all avatars
[17Nov2024 02:18:22.662] [Render thread/INFO] [Entity Texture Features/]: emissive suffixes loaded: {_e}.
[17Nov2024 02:18:23.865] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:219) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:174) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:51) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:226) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property null as it does not exist in Block{minecraft:purple_stained_glass_pane}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%231128!/:?]
	at net.minecraft.world.level.block.IronBarsBlock.m_6104_(IronBarsBlock.java:70) ~[client-1.20.1-20230612.114412-srg.jar%231128!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60719_(BlockBehaviour.java:668) ~[client-1.20.1-20230612.114412-srg.jar%231128!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:37) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.isFaceVisible(BlockRenderer.java:151) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:124) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:139) ~[embeddium-0.3.31+mc1.20.1.jar%23814!/:?]
	... 4 more
[17Nov2024 02:18:23.872] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID acf4b281-eff1-41fc-a3a5-660fa63c775a
[17Nov2024 02:18:23.883] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ae29d9dd-1306-4cfc-848c-82ed6d70d5ae

**Comment by lSherozl** [comment]
https://github.com/quiqueck/BetterEnd/issues/398 Same block type is referenced in this issue

**Comment by lSherozl** [comment]
Same issue is referenced here https://github.com/quiqueck/BetterEnd/issues/475
