### ISSUE TITLE
[Better End Potato Edition 1.16.5] Biome Provider mixins cause Explorer's Compass to become unable to list available structures

### ISSUE THREAD

**Issue by Kaleidio** [MCTeamPotato/Kasualix-Issue-Tracker#20]
```[04Aug2023 09:33:32.905] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.world.biome.provider.BiomeProvider.func_226838_a_(SourceFile:136) ~[?:?]
	at net.minecraft.world.biome.provider.BiomeProvider$$Lambda$19892/400394764.test(Unknown Source) ~[?:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_51]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_51]
	at net.minecraft.world.biome.provider.BiomeProvider.func_226839_b_(SourceFile:136) ~[?:?]
	at net.minecraft.world.biome.provider.BiomeProvider$$Lambda$19891/619269080.apply(Unknown Source) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[?:1.8.0_51]
	at net.minecraft.world.biome.provider.BiomeProvider.func_205004_a(SourceFile:136) ~[?:?]
	at com.chaosthedude.explorerscompass.util.StructureUtils.getStructureDimensions(StructureUtils.java:108) ~[?:1.16.5-1.1.2-forge]
	at com.chaosthedude.explorerscompass.util.StructureUtils.getDimensionsForAllowedStructures(StructureUtils.java:117) ~[?:1.16.5-1.1.2-forge]
	at com.chaosthedude.explorerscompass.items.ExplorersCompassItem.func_77659_a(ExplorersCompassItem.java:50) ~[?:1.16.5-1.1.2-forge]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:216) ~[?:?]
...```

**Comment by Kaleidio** [comment]
closing due to false report, some other mod is at fault
