### ISSUE TITLE
Mixin Conflict Helper show conflicts about Redirector

### ISSUE THREAD

**Issue by tacogerbil** [MCTeamPotato/Kasualix-Issue-Tracker#59]
Lunching my client it crashes.  Had to go back to previous versions.  
MC 1.19.2
redirector-1.19.2-3.4.0-fabric.jar

[Redirector]() is conflicting with [Sodium](https://github.com/CaffeineMC/sodium-fabric).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_918::redirectDirections with priority 10 cannot inject into net/minecraft/class_918::method_23182(Lnet/minecraft/class_1087;Lnet/minecraft/class_1799;IILnet/minecraft/class_4587;Lnet/minecraft/class_4588;)V merged by me.jellysquid.mods.sodium.mixin.features.item.MixinItemRenderer with priority 1000 [ -> redirect$hdo01e$redirector$redirectDirections()[Lnet/minecraft/class_2350; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_1921.<clinit>(class_1921.java:436)
	at com.tterrag.registrate.builders.BlockBuilder.lambda$registerLayers$5(BlockBuilder.java:175)
	at com.tterrag.registrate.fabric.EnvExecutor.runWhenOn(EnvExecutor.java:10)
	at com.tterrag.registrate.builders.BlockBuilder.registerLayers(BlockBuilder.java:175)
	at com.tterrag.registrate.AbstractRegistrate$Registration.lambda$register$0(AbstractRegistrate.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:117)
	at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:195)
	at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:172)
	at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:11)
	at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:171)
	at com.simibubi.create.Create.onInitialize(Create.java:111)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- accurateblockplacement 1.0.17
- adorn 3.9.1+1.19.2
- ambientsounds 5.2.13
- amecs 1.3.8+mc.1.19-rc2
- amecsapi 1.5.1+mc22w17a via mousewheelie
- animatica 0.5+1.19
- appleskin 2.4.1+mc1.19
- architectury 6.5.85
- attributefix 17.2.7
- badpackets 0.2.2
- balm-fabric 4.6.0
- barteringstation 4.0.3
- beachparty 1.0.12
- betterbeds 1.2.0
- betterdeserttemples 1.19.2-Fabric-2.2.2
- betterdungeons 1.19.2-Fabric-3.2.1
- betterf3 4.0.0
- betterfortresses 1.19.2-Fabric-1.0.6
- betterfpsdist 1.19-2.4
- bettermineshafts 1.19.2-Fabric-3.2.0
- betteroceanmonuments 1.19.2-Fabric-2.1.0
- betterstrongholds 1.19.2-Fabric-3.2.0
- betterwitchhuts 1.19.2-Fabric-2.1.0
- blanket-client-tweaks 1.1.2
- blastingsand 1.19.2-11
- block_limit_fix 1.0.3-fabric
- blue_endless_jankson 1.2.1 via doapi
- bobby 4.0.1
- bookshelf 16.3.20
- bouncierbeds 2.1
- bridgingmod 2.1.1+1.19.2.fabric
- caffeineconfig 1.0.0+1.17 via sodium-extra
- cardinal-components-base 5.0.2 via polymorph
- cardinal-components-block 5.0.2 via polymorph
- cardinal-components-chunk 5.0.2 via puzzleslib
- cardinal-components-entity 5.0.2 via polymorph
- cardinal-components-item 5.0.2 via polymorph
- cardinal-components-world 5.0.2 via puzzleslib
- carpeted 1.19.2-1.4
- carryon 2.1.1.21
- chat_heads 0.10.20
- chatsigninghider 1.19.2-1.0.0
- chime 1.3.0
- chipped 2.1.5
- chiselsandbits 1.3.142
- chunkloaders 1.2.7
- chunky 1.3.38
- citresewn 1.1.2+1.19.2
- citresewn-defaults 1.1.2+1.19.2 via citresewn
- clickadv 3.0
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.3.103
- clutter 1.19.2-0.2.1
- coat 1.0.0-beta.20+mc22w17a via mousewheelie
- cobblemon 1.3.1+1.19.2
- cobblemon_fortuneableevostones_mr 1.0
- cobblemon_spawn_notification 1.4.0
- cobblemonbreakouts 1.0.6
- cobblepedia 0.4.4+1.19.2
- collective 6.65
- com_electronwill_night-config_core 3.6.5 via couplings
- com_electronwill_night-config_toml 3.6.5 via couplings
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_esotericsoftware_yamlbeans_yamlbeans 1.15 via emojiful
- com_github_llamalad7_mixinextras 0.2.0-beta.10 via immediatelyfast
- com_github_zsoltmolnarrr_tinyconfig 2.3.2 via dungeon_difficulty
- com_google_code_findbugs_jsr305 3.0.2 via create
- com_typesafe_config 1.4.2 via bobby
- common-economy-api 1.0.0 via universal_shops
- common-protection-api 1.0.0 via htm
- conditional-mixin 0.3.0 via moreculling
- connectedglass 1.1.7
- connectiblechains 2.1.4+1.19.2
- continuity 2.0.2+1.19
- couplings 1.9.1+1.19
- craftingcraft 13.0.0
- craftingtweaks 15.1.8
- crawl 0.11.1
- create 0.5.1-c-build.1160+mc1.19.2
- create_cobblemon_compat 1.0.0
- create_dragon_lib 1.0.1 via create_enchantment_industry
- create_enchantment_industry 1.0.1
- create_jetpack 3.3.1
- create_renewableores_mr 1
- create_so 1.5+fabric-1.19.2
- createaddition 20230723a
- createdeco 1.3.3-1.19.2
- creategoggles 0.5.5.c
- creativecore 2.9.3
- ctm 1.0.1+1.19
- cullleaves 3.0.1
- cupboard 1.19.2-1.9
- customsplashscreen 1.2.0
- dankstorage 1.19.2-4.3
- decorative_blocks 3.1.1
- diagonalfences 4.2.6
- diagonalwindows 4.0.2
- disenchanter 0.1.7+1.19
- doapi 1.1.0
- dripstone_fluid_lib 2.0.1 via milk
- dungeon_difficulty 2.0.5+1.19
- dungeons_arise 2.1.56
- durabilitytooltip 1.1.5
- easymagic 4.3.3
- emojiful 4.0.4
- enchanted-vertical-slabs 1.8
- enchanting-table-descriptions 0.1.0+1.19
- enchantinginfuser 4.2.2
- enchdesc 13.0.14
- enderchests 1.1.1
- entangled 1.3.16
- entity_model_features 0.2.13
- entity_texture_features 4.5.1
- entityculling 1.6.1-mc1.19.2
- everycomp 1.19.2-2.5.5
- excessive_building 1.3.0.2-1.19.2
- exlineawnings 1.1.3
- expandedstorage 8.3.4
- experiencebugfix 19
- extendedgears 2.1.0-1.19.2-0.5.1.c-fabric
- fabric-api 0.76.1+1.19.2
- fabric-api-base 0.4.15+8f4e8eb390 via moremcmeta_emissive_plugin
- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.1.1+16f1e31390 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90 via fabric-api
- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
- fabric-containers-v0 0.1.42+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.2+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.3.0+4bc6e26290 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.9+413cbbc790 via fabric-api
- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
- fabric-events-lifecycle-v0 0.2.36+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.6+b7d1888890 via fabric-api
- fabric-item-groups-v0 0.3.39+9244241690 via fabric-api
- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
- fabric-language-kotlin 1.10.10+kotlin.1.9.10
- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
- fabric-loot-api-v2 1.1.13+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.16+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.24+33fbc73890 via fabric-api
- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.12+def3f86d90 via fabric-api
- fabric-networking-v0 0.3.29+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.2.2+d8ef690890 via fabric-api
- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via htm
- fabric-recipe-api-v1 1.0.2+413cbbc790 via fabric-api
- fabric-registry-sync-v0 0.9.33+9244241690 via fabric-api
- fabric-renderer-api-v1 1.2.1+1adbf27790 via moremcmeta_emissive_plugin
- fabric-renderer-indigo 0.8.0+1adbf27790 via moremcmeta_emissive_plugin
- fabric-renderer-registries-v1 3.2.24+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
- fabric-rendering-v0 1.1.27+df3654b390 via fabric-api
- fabric-rendering-v1 1.12.1+d8ef690890 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.4+edbdcddb90 via moremcmeta_emissive_plugin
- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.14.22
- fallingleaves 1.13.0+1.19.2
- fallingtree 3.10.0
- faster_entity_animations 1.5.7
- faux-custom-entity-data 2.0.2
- ferritecore 5.0.3
- feytweaks 1.19-1.2.6
- fiber 0.23.0-2 via patchouli
- fightorflight 0.4.11-12
- firespreadtweaks 2.3
- flamearrows 1.19.2-11
- flightlib 1.1.0 via create_jetpack
- flywheel 0.6.9-6 via create
- forge_tags 3.0 via create
- forgeconfigapiport 4.2.11
- ftbchunks 1902.4.2-build.302
- ftblibrary 1902.4.1-build.236
- ftbteams 1902.2.13-build.100
- full_slabs 3.3.6
- fusion 1.0.5
- geckolib3 3.1.40
- graphlib 0.3.6+1.19.2 via wiredredstone
- grapplemod 1.19.2-v1.7
- gravelminer 13.0.0
- handcrafted 2.0.6
- hangglider 4.0.0
- hdskins 6.10.2+1.19.2
- headfix 1.2.0
- highlight 1.0.0
- hologram-api 0.2.2+1.19 via universal_shops
- hotbarcycle 1.1.1
- htm 1.1.6
- icarus 1.14
- iceberg 1.0.46
- immediatelyfast 1.2.3+1.19.2
- immersive_paintings 0.6.5+1.19.2
- indium 1.0.9+mc1.19.2
- infinitybuttons 4.0.1-mc1.19.2
- ingredient-extension-api 3.0.6
- interference 1.4.2 via led
- inventoryhud 3.4.7
- io_github_douira_glsl-transformer 2.0.0-pre13 via iris
- io_leangen_geantyref_geantyref 1.3.13 via bobby
- iris 1.6.6
- irisflw 0.2.1
- itemborders 1.1.6
- itemcounts 1.4.1+mc1.19.2
- itemrename 1.0.3
- java 17
- jei 11.6.0.1018
- jepp 1.19.2-1.1.0
- jmxl 1.1 via led
- kanos_config 0.3.1+1.14.4-1.19 via statement
- kirin 1.15.3+1.19.2 via hdskins
- kleeslabs 12.3.0
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.2.0+1.19.2
- lazydfu 0.1.3
- led 1.3.0
- legendarytooltips 1.3.3
- libblockattributes_core 0.11.1 via libmultipart_deps_container
- libmultipart 0.8.2 via libmultipart_deps_container
- libmultipart_compat 0.8.2 via libmultipart_deps_container
- libmultipart_deps_container 0.8.2 via wiredredstone
- libnetworkstack 0.7.1 via libmultipart_deps_container
- lighty 1.3.0+1.19.2
- liquidburner 1.19.2-0.5
- lithium 0.11.1
- lmft 1.0.2+1.19
- lmp-compat 0.2.3+1.19.2 via wiredredstone
- luphieclutteredmod 2.1
- maxhealthfix 8.0.1
- mcwbridges 2.1.0
- mcwdoors 1.1.0
- mcwfences 1.0.7
- mcwfurnitures 3.2.0b
- mcwlights 1.0.6
- mcwpaths 1.0.3
- mcwroofs 2.2.4
- mcwtrpdoors 1.1.1
- mcwwindows 2.2.0
- micalibria 2.1.3 via full_slabs
- midnightcontrols 1.7.4+1.19
- midnightlib 1.0.0
- milk 1.0.51 via create
- mimic 1.2.38
- minecraft 1.19.2
- minepop 0.0.1-1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- mm 2.3 via crawl
- mo_glass 1.6.1-MC1.19.2
- modelfix 1.8
- modernfix 5.7.2+mc1.19.2
- modmenu 4.2.0-beta.2
- moonlight 1.19.2-2.2.44
- more_slabs_stairs_and_walls 2.4.0+1.19.2
- moreculling 1.19.1-0.17.0
- morecullingextra 1.1-backport_1.19.2
- moremcmeta 1.19.2-4.2.3
- moremcmeta_animation_plugin 1.19.2-1.0.0 via moremcmeta
- moremcmeta_emissive_plugin 1.19.2-1.1.1
- moremcmeta_json_parser_plugin 1.19.2-1.1.0 via moremcmeta
- moremcmeta_properties_parser_plugin 1.19.2-1.1.2 via moremcmeta
- moremcmeta_texture_plugin 1.19.2-1.0.0 via moremcmeta
- mousewheelie 1.12.2+mc1.19.2
- mr_edf_remastered 4.3
- nbtgrab 1.1
- net_lenni0451_reflect 1.2.1 via immediatelyfast
- netherportalfix 10.0.1
- nightlights 1.1
- openblocks 0.0.2-1.19.X
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.11.1 via iris
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols
- org_javassist_javassist 3.28.0-GA via yungsapi
- org_jetbrains_kotlin_kotlin-reflect 1.9.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.9.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_lz4_lz4-pure-java 1.8.0 via chiselsandbits
- org_reflections_reflections 0.10.2 via betterdeserttemples
- org_spongepowered_configurate-core 4.1.2 via bobby
- org_spongepowered_configurate-hocon 4.1.2 via bobby
- owo 0.9.3+1.19
- packet_tweaker 0.3.0+1.18.2 via server_translations_api
- paintings 10.2.4.0
- patchouli 1.19.2-77-FABRIC
- picturesign 1.4.1
- placeholder-api 2.0.0-pre.1+1.19.2 via itemrename
- polymer 0.2.28+1.19.2 via universal_shops
- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
- polymorph 0.46.4+1.19.2
- porting_lib_accessors 2.1.1096+1.19.2 via create
- porting_lib_attributes 2.1.1096+1.19.2 via porting_lib_obj_loader
- porting_lib_base 2.1.1096+1.19.2 via create
- porting_lib_common 2.1.1096+1.19.2 via porting_lib_obj_loader
- porting_lib_constants 2.1.1096+1.19.2 via porting_lib_obj_loader
- porting_lib_entity 2.1.1096+1.19.2 via create
- porting_lib_extensions 2.1.1096+1.19.2 via create
- porting_lib_fake_players 2.1.1096+1.19.2 via create
- porting_lib_lazy_registration 2.1.1096+1.19.2 via porting_lib_base
- porting_lib_loot 2.1.1096+1.19.2 via porting_lib_base
- porting_lib_model_generators 2.1.1096+1.19.2 via porting_lib_base
- porting_lib_model_loader 2.1.1096+1.19.2 via porting_lib_obj_loader
- porting_lib_models 2.1.1096+1.19.2 via porting_lib_base
- porting_lib_networking 2.1.1096+1.19.2 via create
- porting_lib_obj_loader 2.1.1096+1.19.2 via create
- porting_lib_transfer 2.1.1096+1.19.2 via create
- presencefootsteps 1.6.4
- pride 1.1.2+1.19 via lambdynlights
- prism 1.0.3
- projectile_damage 3.2.1+1.19
- puzzleslib 4.4.3
- railways 1.5.1+fabric-mc1.19.2
- raised 1.2.2
- reach-entity-attributes 2.3.0 via create
- realisticfirespread 1.19-2
- rechiseled 1.1.4
- rechiseledcreate 1.0.0
- redirector 1.19.2-3.4.0
- reeses-sodium-options 1.6.4+mc1.19.2-build.93
- registrate-fabric 1.1.58-MC1.19.2 via create
- reputation 0.2.2+wthit.1.19
- resourcefullib 1.1.24
- roberts_collection 1.0.3
- rpgdifficulty 1.3.12
- rptweaks 1.0.1-1.19
- rrls 1.19.2-3.1.1-fabric
- saeculariacaudices 1.0.16 via chiselsandbits
- scena 1.0.95 via chiselsandbits
- seafoamsdyeableblocks 1.3.0
- seamless 1.3.1
- serialization_hooks 0.3.26 via porting_lib_base
- server_translations_api 1.4.18+1.19.2 via htm
- sgui 1.1.5+1.19.1 via universal_shops
- shards 1.0
- shetiphiancore 1.3.4
- simplemagnets 1.1.9
- slabstoblocks 1.19.2-0
- smoothboot 1.19-1.7.1
- smoothchunk 1.19.2-3.1
- sodium 0.4.4+build.18
- sodium-blendingregistry 0.4.4.1
- sodium-extra 0.4.14+mc1.19.2-build.80
- soulbound 0.1
- sound_physics_remastered 1.19.2-1.2.1
- spectrelib 0.12.5+1.19.2 via polymorph
- spiderstpo 1.19.2-2.0.3
- spruceui 4.1.0+1.19.2 via lambdynlights
- stackrefill 4.0
- starlight 1.1.1+fabric.ae22326
- statement 4.2.4+1.14.4-1.19.1 via micalibria
- statement_vanilla_compatibility 1.0.1+1.16.5-1.17 via statement
- stb 5.0.0
- stoneworks 4.0.1
- supermartijn642configlib 1.1.8
- supermartijn642corelib 1.1.12+b
- symbol-chat 1.19.2-0.5.1
- tawct 1.4.3+1.19.2
- team_reborn_energy 2.3.0 via createaddition
- tempered_glass 1.1.0
- terraform-wood-api-v1 4.2.0 via doapi
- tesseract 1.0.35a
- toms_storage 1.5.9
- totem_cooldown 1.0
- transparent 5.1.2
- trashcans 0.0.2-1.19.X
- trashslot 12.1.0
- travelersbackpack 1.19.2-8.2.28
- trinkets 3.4.2
- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
- tweed4_base 1.7.1+mc22w17a via mousewheelie
- tweed4_data 1.2.1+mc22w17a via mousewheelie
- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
- tweed4_tailor_coat 1.1.3+mc22w17a via mousewheelie
- tweed4_tailor_lang_json_descriptions 1.1.0+mc22w17a via mousewheelie
- tweed4_tailor_screen 1.1.4+mc22w17a via mousewheelie
- universal_shops 1.0.3+1.19.2
- visualworkbench 4.2.4
- walllanterns 1.4.0-1.19
- wands 2.6.6-release
- wi_zoom 1.4-MC1.19.2
- wiredredstone 0.4.19+1.19.2
- world_of_colour_plus 1.0.0
- worldedit 7.2.12+6240-87f4ae1
- worldeditcui 1.19.2+01
- wthit 5.19.0
- xaerominimap 23.8.0
- yungsapi 1.19.2-Fabric-3.8.9
- yungsbridges 1.19.2-Fabric-3.1.0
- yungsextras 1.19.2-Fabric-3.1.0
- yuushya 2.1.1
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.22

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by Kasualix** [comment]
It won't crash your game. Removing MCH and let it go. Further, I don't think MCH should report the mixin conflicts that never crash the game, maybe you can report this to it?

**Comment by tacogerbil** [comment]
So there's no actual conflict?

**Comment by Kasualix** [comment]
At least total harmless conflict.

**Comment by Kasualix** [comment]
https://github.com/isXander/MixinConflictHelper/issues/11
It seems it's already reported

**Comment by tacogerbil** [comment]
Well daing... I apologize for wasting your time :)
